### ISSUE TITLE
Webpack2 breaking change

### ISSUE THREAD

**Issue by crunchex** [video-dev/clappr-rtmp-plugin#73]
I'm getting an error in a project using webpack2:

Module not found: Error: Can't resolve 'raw' in '/home/crunchex/myproject/node_modules/clappr-rtmp/src'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'raw-loader' instead of 'raw',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed

Not sure how to submit a PR with a fix as I'm having issues rebuilding the package with the Adobe AIR sdk business.

**Comment by hxl-dy** [comment]
I created the PR: https://github.com/flavioribeiro/clappr-rtmp-plugin/pull/74
