### ISSUE TITLE
Unable to play a 360 video with this plugin

### ISSUE THREAD

**Issue by shivangikanitkar** [video-dev/clappr-rtmp-plugin#88]
Can I use this player to play a 360 video streamed using RTMP?
Is there a way to integrate the RTMP and Video360 plugins together?

**Comment by shivangikanitkar** [comment]
Please help?

**Comment by flavioribeiro** [comment]
In order to add 360 support to this you would need to integrate with [this](http://www.adobe.com/devnet/flashplayer/articles/spherical-video-support-flash-air.html), parse 
 360 metadata, etc.
