### ISSUE TITLE
Your browser does not support the playback of this video.

### ISSUE THREAD

**Issue by saad4s** [video-dev/clappr-rtmp-plugin#95]
```
<html>
<head>
<title>Clappr Player</title>
<script src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/video-dev/clappr-rtmp-plugin@latest/dist/rtmp.min.js"></script>
</head>
<body>
  <div id="player"></div>
  <script>
	var player = new Clappr.Player({
	    source: "rtmp://192.168.4.136:1935/live/test",
	    parentId: "#player",
	    plugins: {'playback': [RTMP]},
	    rtmpConfig: {
	        swfPath: 'dist/assets/RTMP.swf',
	        scaling:'stretch',
	        playbackType: 'live',
	        bufferTime: 1,
	        startLevel: 0,
	        switchRules: {
	            "SufficientBandwidthRule": {
	                "bandwidthSafetyMultiple": 1.15,
	                "minDroppedFps": 2
	            },
	            "InsufficientBufferRule": {
	                "minBufferLength": 2
	            },
	            "DroppedFramesRule": {
	                "downSwitchByOne": 10,
	                "downSwitchByTwo": 20,
	                "downSwitchToZero": 24
	            },
	            "InsufficientBandwidthRule": {
	                "bitrateMultiplier": 1.15
	            }
	        }
	    },
	});
  </script>
</body>
</html>
```

On my PC with windows 7 and browser with flash seem all OK
![rtmp](https://user-images.githubusercontent.com/17269909/35481507-f23e7504-044e-11e8-85c6-e1ecc0344944.PNG)

**Comment by sornbarang** [comment]
yeah the same issue. who can help please!

**Comment by xiaocaimi** [comment]
IE11, same issue,
when I update my flash player,it's has been ok

**Comment by ismjt** [comment]
maybe you can try to enable browser's Adobe Flash support, such as Chrome's website setting of Flash

**Comment by topxj** [comment]
chrome://settings/content/flash

add

**Comment by contra** [comment]
This could be fixed if the plugin quit checking for Browser.hasFlash, since that would show "Click to enable flash" in lieu of the video.

**Comment by flavioribeiro** [comment]
@contra is it possible to send a PR with that?

**Comment by contra** [comment]
@flavioribeiro Would probably be quicker for you since I have a fork with a bunch of other changes on it already.

https://github.com/video-dev/clappr-rtmp-plugin/blob/master/src/main.js#L230 just remove `&& Browser.hasFlash`

**Comment by flavioribeiro** [comment]
@contra the `Browser.hasFlash()` conditional on `canPlay` makes sense to me. What I imagine it's happening is that the [hasFlash](https://github.com/clappr/clappr/blob/004e69133c0b2cf5d6e061050c82ec943b6f8f85/src/components/browser/browser.js#L17) implementation on clappr is outdated/non-compatible with the latest browsers? 

Also curious in your fork. I'm wondering how could benefit from some of your changes. Is that [this](https://github.com/video-dev/clappr-rtmp-plugin/compare/master...contra:master)  fork you're talking about?

**Comment by contra** [comment]
@flavioribeiro 	In latest browsers (chrome, firefox, safari) you have no way to know if the user has flash installed. This is intentional by the browser vendors - flash does not appear in `navigator.plugins`. The only thing you can do is try to load the flash anyways, which will display "Click to load flash" over the container. Clicking this loads the plugin and authorizes that domain for the remainder of the session.

**Comment by flavioribeiro** [comment]
done 2b56b732569cec7b15d81cd439e26bd06d1c9bd1
